version: '3.9'

services:
    volta:
        image: rabbitmq:3.11.9-management-alpine
        container_name: volta_tests
        environment:
            RABBITMQ_DEFAULT_USER: volta
            RABBITMQ_DEFAULT_PASS: volta
        ports:
            - "5672:5672"